<img src='https://upload.wikimedia.org/wikipedia/commons/3/3a/Gray808.png'>

**Task**: segment a collection of nerves called the Brachial Plexus (BP) in ultrasound images

# visualization of prepared data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

imgs_id_test = np.load('../src/brachial/imgs_id_test.npy')
imgs_mask_train = np.load('../src/brachial/imgs_mask_train.npy')
imgs_test = np.load('../src/brachial/imgs_test.npy')
imgs_train = np.load('../src/brachial/imgs_train.npy')

**id** of each test picture:

In [3]:
imgs_id_test

array([ 1, 10,  2,  3,  4,  5,  6,  7,  8,  9])

test img **representation**

In [35]:
df_test = pd.Panel4D(imgs_test)
df = df_test[1][0]
df.head()

0    1    2    3    4    5    6    7    8    9   ...   570  571  572  573  \
0    0  188  172  168  162  159  159  159  161  162 ...   119  115  113  112   
1    0  255  255  255  255  255  255  255  255  255 ...   194  191  184  182   
2    0  255  255  255  255  255  255  255  253  252 ...   215  211  203  200   
3    0  179  164  158  157  157  158  161  165  166 ...   204  205  205  206   
4    0  161  135  134  132  133  128  132  137  141 ...   218  224  234  240   

   574  575  576  577  578  579  
0  112  114  116  116  115  114  
1  182  184  186  185  177  172  
2  204  204  208  205  192  185  
3  204  196  185  184  179  179  
4  239  224  210  199  191  196  

[5 rows x 580 columns]

In [ ]:
DataFrame.hist(df)

In [21]:
sorted(df[1])
counts = np.bincount(sorted(df[1]))


array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  3,  0,  0,  1,  5,  2,  1,  0,  0,  1,  2, 14,  0,
        1,  0,  0,  2,  2,  1,  1,  7,  1,  0,  3,  0,  4,  2,  1,  0,  0,
        1,  7,  0,  2,  1,  6,  0,  0,  7,  3,  0,  2,  0,  3,  0,  5,  2,
        0,  3,  5,  3,  0,  4,  5,  9,  6,  1,  0,  0,  1,  4,  0,  1,  2,
        2,  0,  1,  3,  2,  3,  5,  4,  0,  2,  0,  1,  2,  3,  1,  0,  3,
        1,  2,  1,  0,  1,  0,  1,  0,  1,  2,  0,  3,  0,  0,  0,  3,  0,
        0,  2,  1,  0,  3,  3,  3,  1,  1,  0,  0,  2,  0,  1,  0,  1,  1,
        0,  2,  0,  1,  1,  1,  2,  0,  1,  2,  0,  0,  1,  0,  0,  0,  1,
        1,  0,  1,  1,  0,  2,  0,  5,  2,  3,  1,  0,  3,  2,  0,  1,  1,
        0,  1,  0,  1,  2,  1,  0,  0,  0,  8,  4, 20, 98,  1, 13,  0,  3,
        1,  0,  1,  4,  0,  2,  1,  1,  1,  0,  2,  0,  1,  0,  0,  0,  0,
        0,  1,  0,  0,  0

In [26]:
np.argmax(counts)

199

In [56]:
sorted(df_test[1][0][1].unique())
dfr_test = pd.DataFrame(df_test[1][0][1])
dfr_test.tail()

1
415  42
416  42
417  42
418  42
419  42

In [19]:
imgs_test.shape, imgs_test[1][0][1]

((10, 1, 420, 580),
 array([  0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 250, 240,
        244, 246, 245, 239, 236, 238, 240, 246, 250, 255, 252, 244, 239,
        245, 250, 254, 255, 255, 255, 255, 251, 248, 247, 247, 246, 245,
        247, 250, 247, 239, 243, 250, 253, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        251, 248, 247, 246, 246, 246, 241, 241, 246, 255, 255, 255, 255,
        244, 240, 244, 248, 255, 255, 255, 255, 244, 248, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 253, 250, 247, 245, 245, 247, 251, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 254, 251, 250, 248, 248, 255, 255, 255,
        255, 255, 255, 250, 247

train mask

In [12]:
type(imgs_mask_train), (imgs_mask_train.shape)

(numpy.ndarray, (12, 1, 420, 580))